### ISSUE TITLE
Docker file setup in Jetbot

### ISSUE THREAD

**Issue by lohitslohit** [NVIDIA-AI-IOT/jetbot#499] opened 2021-11-21 17:37 UTC
This is the error I am getting while setup the docker in jetbot.

![be2936100775a75e63670fba4a0de6d3eebbaa9b_2_1035x490](https://user-images.githubusercontent.com/59111894/142771624-11d8c99e-0fa1-4c9b-9233-cfe48c2c5231.jpg)

**Comment by santaimpersonator** [comment] 2021-11-23 22:24
This seems like a duplicate of: https://github.com/NVIDIA-AI-IOT/jetbot/issues/406

* See this comment here: https://github.com/NVIDIA-AI-IOT/jetbot/issues/406#issuecomment-837006950

There is already a [pull request for this issue](https://github.com/NVIDIA-AI-IOT/jetbot/pull/456), so you can probably close this since it is also a duplicate.

**Closed** 2022-07-18 20:31 UTC
