### ISSUE TITLE
Road Following very slow using Waveshare Jetbot

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [NVIDIA-AI-IOT/jetbot#398] opened 2021-03-02 15:01 UTC
Hi, I have got a Waveshare Jetbot where I trained for the Road Following task but on a straight path it starts wobling left and right and if I reduce the steering gain than it is not able to make turns properly.

Is there any way that I could avoid the wobling and at the same time perform turns normally?

Also, slightly off topic but what is steering kd used for in the road following adjustment sliders? 

Thanks and Best Regards
Abu

**Comment by jaybdub** [comment] 2021-03-20 18:54
Hi @abuelgasimsaadeldin ,

Thanks for reaching out!

The KD value is the "derivative" value.  

1.  Proportional gain ("steering gain" in notebook):  Increases proportionally with how far away we are from our target
2. Derivative gain ("steering kd" in notebook):  Increases proportionally with how _fast_ we're moving towards or away from our target.  For example, if currently facing our target, but we know from the last sample that we're quickly turning right, KD would still tell us to turn left.

KD is typically used to dampen the response, which might help with wobbliness.  The issue is, that at certain frame rates, or because of "noise", KD can actually cause sharp jitters. 

Depending on the platform you're using, the dynamics will vary.  It might be necessary to lower the "forward" speed of the robot on a very narrow path like LEGO city road in order to make the turns.

Please let me know if this helps or you have any questions.  Hopefully we can reach something that runs smoothly :)

Best,
John

**Closed** 2022-07-15 22:07 UTC
