### ISSUE TITLE
How to combine road following and object detection?

### ISSUE THREAD

**Issue by yangrisheng** [NVIDIA-AI-IOT/jetbot#494] opened 2021-11-09 06:17 UTC
How to combine road following and object detection?
Do there have some code about that?

**Comment by santaimpersonator** [comment] 2021-11-23 21:48
Seems like a duplicate of: https://github.com/NVIDIA-AI-IOT/jetbot/issues/478

**Closed** 2022-07-18 20:31 UTC
