### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA-AI-IOT/jetbot#508] opened 2021-12-26 03:22 UTC
For Example 4 - Object Following (Please refer to [JetBot Wiki Examples](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/examples) ), in my case, the very **FIRST** 2 lines brought me issues:
```console
from jetbot import ObjectDetector

model = ObjectDetector('ssd_mobilenet_v2_coco.engine')
```

```console
AttributeError                            Traceback (most recent call last)
<ipython-input-1-78c468b59bd4> in <module>
      1 from jetbot import ObjectDetector
      2 
----> 3 model = ObjectDetector('ssd_mobilenet_v2_coco.engine')

~/.local/lib/python3.6/site-packages/jetbot-0.4.3-py3.6.egg/jetbot/object_detection.py in __init__(self, engine_path, preprocess_fn)
     27         load_plugins()
     28         self.trt_model = TRTModel(engine_path, input_names=[TRT_INPUT_NAME],
---> 29                                   output_names=[TRT_OUTPUT_NAME, TRT_OUTPUT_NAME + '_1'])
     30         self.preprocess_fn = preprocess_fn
     31 

~/.local/lib/python3.6/site-packages/jetbot-0.4.3-py3.6.egg/jetbot/tensorrt_model.py in __init__(self, engine_path, input_names, output_names, final_shapes)
     57         with open(engine_path, 'rb') as f:
     58             self.engine = self.runtime.deserialize_cuda_engine(f.read())
---> 59         self.context = self.engine.create_execution_context()
     60 
     61         if input_names is None:

AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

Any suggestions?

**Comment by santaimpersonator** [comment] 2022-01-05 17:07
This is a duplicate of https://github.com/NVIDIA-AI-IOT/jetbot/issues/430

**Closed** 2022-07-15 21:39 UTC
