### ISSUE TITLE
Trouble with ROS2 communication between PC and Docker

### ISSUE THREAD

**Issue by lalaorome** [NVIDIA-AI-IOT/jetbot#534] opened 2022-04-29 16:21 UTC
Hi all,

I am new to ROS and ROS2 and I am trying to setup a mutli-agent framework using Nvidia Jetbots and a central PC.

The Jetson Nanos of the jetbots are flashed with JetPack version 4.5.0 and I am using ROS2 Galactic distro through the jetson containers provided by NVIDIA : [https://github.com/dusty-nv/jetson-co...](https://github.com/dusty-nv/jetson-containers)

My central PC is running on Ubuntu 20.04.04 and I installed ROS2 Galactic distro using the Debian Packages.

Both are connected to the same local network which I didn't configured so I don't have much information on it.

When I am trying to run a basic talker using `ros2 run demo_nodes_cpp talker` on my JetBot and a listener on my Central PC using `ros2 run demo_nodes_cpp listener` everything work fine. However when I try to see the node list for example using the `ros2 node list` command, the command just hangs until I stop it using Ctrl+c. I have the same problem when using the `echo` command or `ros2 topic list` for example.

I am really confused and don't really know what to do. I tried to search on internet but didn't find something relevant since my setup is really specific.

Please tell me if some of you have a solution to this problem I would really appreciate it.

Thanks in advance

**Comment by jaybdub** [comment] 2022-07-15 21:31
Hi @lalaorome ,

Thanks for reaching out!

Apologies, I don't know exactly what would be the issue here.

That said, I'd recommend checking out [nvidia-isaac-ros-common](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common), which seems to have some Dockerfiles for building a reproducible ROS2 setup for Jetson.

I hope this helps, I'm going to close this issue for now since we don't use ROS2 in this project, but please let me know if you have any questions or feel free to re-open as needed.

Best,
John

**Closed by jaybdub** 2022-07-15 21:31 UTC
